### ISSUE TITLE
401 error with valid token

### ISSUE THREAD

**Issue by niklas1375** [Doist/todoist-api-typescript#117]
## Bug description

When using the SDK to create a task, the creation works when using my personal API token (from integrations section in settings) but not with the test token from the App Management console (https://developer.todoist.com/appconsole.html) where I get a 401 error.

## Expected behaviour

The test token from the App Management console should work to enable testing of the integration. According to the [Authorization documentation](https://developer.todoist.com/rest/v1/#authorization) it should be possible to use them interchangeably.

## Is reproducible

Yes

## To reproduce

Create a new App in the App Management console. Generate a test token and use that along with the personal one.
I created a barebone express app with two endpoints. One for the personal, one for the test token. Essentially it only does this:
```javascript
function apiTest(res: Response, tokenName: string) {
  const tokens = {
    personal: "<personal token goes here>",
    test: "<test token goes here>",
  };
  const api = new TodoistApi(tokens[tokenName as keyof {}]);
  api
    .addTask({
      content: "Dummy Task",
    })
    .then((_) => {
      res.send("yay");
    })
    .catch((error) => {
      console.log(error);
      res.send("nay");
    });
}
```

## Steps taken to try to reproduce

I have recreated the App in the App Management but the new token doesn't work either.

## Screenshots

Error message output:
```bash
1] Error
[1]     at /Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/restClient.js:111:37
[1]     at step (/Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/restClient.js:44:23)
[1]     at Object.next (/Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/restClient.js:25:53)
[1]     at /Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/restClient.js:19:71
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (/Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/restClient.js:15:12)
[1]     at request (/Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/restClient.js:106:12)
[1]     at TodoistApi.<anonymous> (/Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/TodoistApi.js:86:75)
[1]     at step (/Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/TodoistApi.js:33:23)
[1]     at Object.next (/Users/XXXXX/dev/personal/sandbox/node_modules/@doist/todoist-api-typescript/dist/TodoistApi.js:14:53) {
[1]   httpStatusCode: 401,
[1]   responseData: 'Forbidden',
[1]   isAuthenticationError: [Function (anonymous)]
[1] }
```

## Version information:

-   Package version: ^1.5.0

**Comment by scottlovegrove** [comment]
This is strange. We use this package in some of our own projects, so I just did what you suggested and created a new app, generated the test token, and got one of our projects to use that token, and it works as expected, fetching the requested data. 

It might be worth putting the value you're passing into `TodoistApi` into a console.log and just ensure that the value is what you are expecting, just to rule that out.

**Comment by niklas1375** [comment]
I retried as recommended, printing the the value and it is the exact expected value but still the 401 error remains. As you can see in the snippet of my initial issue I'm using the exact same way of passing the keys so there's no difference there as well.

Could it be possible that for some reason my account was banned from creating apps? I saw that there's a different error for that in the [Authorization guide](https://developer.todoist.com/guides/#step-1-authorization-request) ("Invalid Application Status") but this hasn't occurred when using the redirect method to get a user token.

**Comment by niklas1375** [comment]
@scottlovegrove the error is still reproducible - as said previously even with the recommended checks. 
However I created a new dummy application in the App Management console and it works. Since I'm only getting a 401 forbidden error and no details I'm still confused and require some help please? :)

**Comment by scottlovegrove** [comment]
@niklas1375 Is it just that one application that is doing this? I've tried test tokens from a number of my own apps (some going back a few years), and all work when creating a task. 

Does the token work if you just do 
```
curl https://api.todoist.com/rest/v2/tasks -H "Authorization: Bearer <token>"
```
If that works, is it just when you want to create/update something that you end up with this error?

**Comment by niklas1375** [comment]
@scottlovegrove the plain call via curl doesn't work either and I get the same plain 401 error.

**Comment by niklas1375** [comment]
I can't analyse this error on my own since the API is a black box to me so I would really appreciate it if there was some help here? Your authentication mechanism is obviously not permitting my request without an obvious reason...

**Comment by scottlovegrove** [comment]
@PotHix I wonder if you may have some insight into what could be causing this when using the REST API. I can't reproduce this myself, but it seems that we are rejecting the user's test token for some reason. Is there any way we can help determine _why_ it's being rejected?

**Comment by PotHix** [comment]
@scottlovegrove is this a recent test token? We did some changes in the past weeks in the REST API and test token to give it more permissions. I suggest regenerating the test token and try again, as I can see this issue is ~30 days old.

**Comment by PotHix** [comment]
@niklas1375 we just deployed a change to fix that today. Can you please try it again?

**Comment by niklas1375** [comment]
@PotHix yes, finally it's working both with the test token as well as the actual token flow using the user's token. Thank you very much!
