### ISSUE TITLE
How to request archived tasks and sort tasks results?

### ISSUE THREAD

**Issue by zabaala** [Doist/todoist-api-typescript#120]
Hello,

How I can request archived tasks with the TodoistApi? 
Is possible too to apply order to the results?

Thanks.

**Comment by scottlovegrove** [comment]
Archived tasks can't be fetched using this package at this time, you would need to use the Sync API's endpoint for this. Please see https://developer.todoist.com/sync/v9/#get-all-completed-items This does not require using the full sync API, you can just use that one endpoint and use the token you would be using in this package.
