### ISSUE TITLE
GetTasks endpoint does not work with ids parameter

### ISSUE THREAD

**Issue by Tobias-Braun** [Doist/todoist-api-typescript#131]
## Bug description

GetTasks endpoint does not work with ids parameter

## Expected behaviour

When calling `todoistApi.getTasks({ids: [1, 2]})` I should get only the tasks with id 1 and 2. (Of course assuming 1 and 2 are valid ids for my account).
However, I get all active tasks, the parameter is ignored.

## Is reproducible

Yes

## To reproduce

Use the `getTasks()` call with one of your accounts and valid ids.

## How to Fix

Your `getTasks()` definition in typescript, specifically the `GetTaskArgs` interface, expects ids to be of type `number[]`. However, your endpoint expects the ids parameter as a string value with comma-separated ids. This clashes and the parameter is therefore ignored.
You can solve the issue by either calling `toString()` on ids or by changing the type definition of the sdk.

**Comment by scottlovegrove** [comment]
Thanks for reporting this @Tobias-Braun, there is a proposed fix in #138. I'll post back here once it's merged in and released.

Be aware though that this fix will be part of the v2 package, which does come with some breaking changes (namely IDs are now strings, and a few fields have been renamed), see here for more details https://developer.todoist.com/rest/v2/#migrating-from-v1

**Comment by Tobias-Braun** [comment]
Thanks @scottlovegrove.
I just fixed the error by calling `toString(`) on the array and ignoring the typescript error.
Will see when I switch to v2, I just use the api for a small task tracking server.

Cheers Mate 🍺

**Comment by scottlovegrove** [comment]
Released with 2.0.3.
