### ISSUE TITLE
How to move a task from one project to another?

### ISSUE THREAD

**Issue by garyking** [Doist/todoist-api-typescript#144]
## Question description

The new REST v2 API, in `updateTask`, doesn't support `projectId` property, like it did in v1. So how can we move a task from one project to another now?

**Comment by henningmu** [comment]
Hi @garyking, 
Unfortunately, this is a limitation of the REST API. We might introduce it in a new version in the future, but for now, you need to use the sync API (https://developer.todoist.com/sync/v8/#move-an-item).
