### ISSUE TITLE
ValidationError: duration is expected but was missing

### ISSUE THREAD

**Issue by dubisdev** [Doist/todoist-api-typescript#248]
## Bug description

Hi all,

I'm getting this error

![image](https://github.com/Doist/todoist-api-typescript/assets/77246331/eb06e6cc-535b-4ebf-ad26-b2bb8f751267)

I think is related to #246 . Maybe the changes hasn't been published in a new version? I'm using 3.0.0

## Expected behaviour

Not breaking when doing a request with the `getTask` method.

## Is reproducible

Yes/No

## To reproduce

It's the same problem that was in #245, and that was fixed in #246. I think it just hasn't been published.

## Version information:

-   Package version:

**Comment by scottlovegrove** [comment]
v3.0.1 has been released which addresses this issue.
