### ISSUE TITLE
getTasks with filter containing comma returns empty result

### ISSUE THREAD

**Issue by dmitry-yudakov** [Doist/todoist-api-typescript#250]
## Bug description

It seems that using `,` in a filter (like 'today, tomorrow') causes the returned result to be empty array while in the UI it works as expected and returns a non-empty result.

## Expected behaviour

I expect the behavior of getting task with a filter to be consistent between Todoist UI and the api.

## Is reproducible

Yes

## To reproduce

Have at least one task with due date "Today".

```
api.getTasks({ filter: 'today, tomorrow', lang: 'en' })
```

## Version information:

-   Package version: 3.0.1, 2.1.2

## Additional information

If I replace `'today, tomorrow'` with  `'today | tomorrow'` I receive one task that is the expected result. Tried also escaping with `\` (which does the job for `[ or ]` inside the filter) but in this case it leads to invalid format error.

I'm currently trying a workaround of splitting the filter string by `,`, embracing the pieces with brackets and then joining with `' | '` (like `today & @30, today & @60` -> `(today & @30) | (today & @60)`) but I'm not completely sure it's absolutely the same.

**Comment by henningmu** [comment]
Thank you for the report, @dmitry-yudakov. We can reproduce this and it points to an API error that we have now reported internally. I'll update you on the progress here.

The workaround you described will return the same tasks. The difference is rendering, in the client apps filters separated by comma each get their own "section" while filters concatenated with `|` pipe do not 👍

**Comment by henningmu** [comment]
Unfortunately, our API doesn't support multiple filters separated by comma. The docs have been updated to reflect this.

In the client apps we solve this, by splitting the filters up manually using this regex:

```js
const subqueries = query.match(/(?:\\,|[^,])+/g)
```

Maybe you can use a similar approach? Otherwise, keep working with the pipe operator, which is also a valid workaround 👍

**Comment by dmitry-yudakov** [comment]
Thank you for the update 👍 
I guess my temporary solution will become permanent for us for the time being 😀 
In our case, we show the unfied list of tasks anyway so it's simpler with just one request.
