### ISSUE TITLE
Types relying on type-fest not working without type-fest installed

### ISSUE THREAD

**Issue by sitek94** [Doist/todoist-api-typescript#254]
## Bug description
The types from `@doist/todoist-api-typescript` that use `type-fest` utility types (e.g. `AddTaskArgs`, `UpdateTaskArgs`, `AddCommentsArgs`) are not working correctly without `type-fest` installed in the project. They show up as `any` type.

## Expected behaviour
The types should work correctly out of the box, without requiring users to install `type-fest` separately.

## Is reproducible
Yes

## To reproduce
1. Create a new TypeScript project
2. Install `@doist/todoist-api-typescript`
3. Try to use a type that relies on `type-fest`, e.g. `AddTaskArgs`
4. Observe that it shows up as `any` type and doesn't provide type checking

![CleanShot 2024-03-09 at 18 36 07](https://github.com/Doist/todoist-api-typescript/assets/58401630/a2c7fd43-a23b-4ce4-b800-d31452e0ae63)

## Steps taken to try to reproduce
1. Installed `type-fest` in the project
2. Observed that the types now work as expected

![CleanShot 2024-03-09 at 18 35 01](https://github.com/Doist/todoist-api-typescript/assets/58401630/e1bb6a44-4ff6-4b42-972d-2c5114bbc400)

## Version information:
- Package version: 3.0.2

## Additional information
It seems like `type-fest` should be a dependency of `@doist/todoist-api-typescript` so that users don't have to install it separately. Could you please consider adding it?

Reproduction without type-fest: https://stackblitz.com/edit/vitejs-vite-hzqubj?file=src%2Findex.ts
Reproduction with type-fest installed: https://stackblitz.com/edit/vitejs-vite-imo1yj?file=src%2Findex.ts

**Comment by henningmu** [comment]
> It seems like type-fest should be a dependency of @doist/todoist-api-typescript so that users don't have to install it separately. Could you please consider adding it?

Either that or as a peer dependency. Would you mind creating a PR for that? 👍
