### ISSUE TITLE
Create an OpenAPI spec so users can generate their own typescript clients

### ISSUE THREAD

**Issue by tonyxiao** [Doist/todoist-api-typescript#256]
This repo would be semi-obsolete if users can generate their own typescript client.

**Comment by henningmu** [comment]
I fully agree 👍

There are internal conversations happening with our API and Backend team, and it looks like we'll get there at one point. However, there's no clear ETA on this 👍

**Comment by tonyxiao** [comment]
What if we "reverse-engineer" an OpenAPI spec and generate a typescript client and publish to NPM that way? It saves us needing to write client code and one of the big benefit of OpenAPI spec is that well, it is just a spec, and anyone can write it we don't need the backend team to change anything to get started.

**Comment by tonyxiao** [comment]
We can also use the spec to generate python / go etc api clients for todoist without needing to separately maintain the on the SDK team.

**Comment by henningmu** [comment]
Sure that could be an option. You have my blessing to create a fork or new project for this 🙌
